site_name: Zebbra Docs
theme:
  name: material
nav:
    - Home: index.md
    - OAuth 2.0 Authentication: oauth_authentication.md
    - Integration Guide: add_integration.md
    - Gusto Integration Example: gusto_example.md
