name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up environment variables
      env:
        ENV_ENCRYPT_PASS: {{ secrets.ENV_ENCRYPT_PASS }}
        AUTH_SECRET: {{ secrets.AUTH_SECRET }}
        AUTH_ALGO: {{ secrets.AUTH_ALGO }}
        AUTH_TOKEN_EXPIRE: {{ secrets.AUTH_TOKEN_EXPIRE }}
        MONGODB_USER: {{ secrets.MONGODB_USER }}
        MONGODB_DB: {{ secrets.MONGODB_DB }}
        MONGODB_PW: {{ secrets.MONGODB_PW }}
        MONGODB_URL: {{ secrets.MONGODB_URL }}

    - name: Set up python-3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd server
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: '5.0'

    - name: Set up db
      run: |
        cd server
        make setup_db_no_source

    - name: Run tests
      run: |
        cd server
        make test
