name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up environment variables
      env:
        DOT_ENV: ${{ secrets.DOT_ENV }}
      run: |
        cd server
        echo $DOT_ENV | base64 --decode > .env

    - name: Set up python-3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd server
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: '5.0'

    - name: Set up db
      run: |
        export
        cd server
        make setup_db

    - name: Run tests
      run: |
        cd server
        ls -la
        make test
