name: Run tests

on: [push]

env:
  ENV_SET: ${{ secrets.ENV_SET }}
  ZEBBRA_BASE_URL: ${{ secrets.ZEBBRA_BASE_URL }}
  ENV_ENCRYPT_PASS: ${{ secrets.ENV_ENCRYPT_PASS }}
  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
  AUTH_ALGO: ${{ secrets.AUTH_ALGO }}
  AUTH_TOKEN_EXPIRE: ${{ secrets.AUTH_TOKEN_EXPIRE }}
  MONGODB_USER: ${{ secrets.MONGODB_USER }}
  MONGODB_DB: ${{ secrets.MONGODB_DB }}
  MONGODB_PW: ${{ secrets.MONGODB_PW }}
  MONGODB_URL: ${{ secrets.MONGODB_URL }}
  XERO_CLIENT_ID: ${{ secrets.XERO_CLIENT_ID }}
  XERO_CLIENT_SECRET: ${{ secrets.XERO_CLIENT_SECRET }}
  GUSTO_CLIENT_ID: ${{ secrets.GUSTO_CLIENT_ID }}
  GUSTO_CLIENT_SECRET: ${{ secrets.GUSTO_CLIENT_SECRET }}
  CACHE_TTL: ${{ secrets.CACHE_TTL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up python-3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd server
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: '5.0'

    - name: Set up db
      run: |
        cd server
        make setup_db

    - name: Run tests
      run: |
        cd server
        make test
